{
 "title": "Docker_Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Container_Service_RAM_USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "grafana_RAM_USAGE", "legendFormat": "__auto" },
    { "expr": "kafka_RAM_USAGE", "legendFormat": "__auto" },
    { "expr": "kafka_ui_RAM_USAGE", "legendFormat": "__auto" },
    {
     "expr": "progetto_prometheus_1_RAM_USAGE",
     "legendFormat": "__auto"
    },
    { "expr": "progetto_db_1_RAM_USAGE", "legendFormat": "__auto" },
    { "expr": "phpmyadmin_RAM_USAGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Container_Service_CPU_USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "grafana_CPU_USAGE", "legendFormat": "__auto" },
    { "expr": "kafka_CPU_USAGE", "legendFormat": "__auto" },
    { "expr": "kafka_ui_CPU_USAGE", "legendFormat": "__auto" },
    { "expr": "phpmyadmin_CPU_USAGE", "legendFormat": "__auto" },
    {
     "expr": "progetto_prometheus_1_CPU_USAGE",
     "legendFormat": "__auto"
    },
    { "expr": "progetto_db_1_CPU_USAGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Container_Module_RAM_USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "progetto_consumer_1_RAM_USAGE", "legendFormat": "__auto" },
    { "expr": "progetto_exporter_1_RAM_USAGE", "legendFormat": "__auto" },
    { "expr": "progetto_notifier_1_RAM_USAGE", "legendFormat": "__auto" },
    { "expr": "progetto_producer_1_RAM_USAGE", "legendFormat": "__auto" },
    { "expr": "progetto_sarima_1_RAM_USAGE", "legendFormat": "{{label_name}}" },
    {
     "expr": "progetto_subscriber_1_RAM_USAGE",
     "legendFormat": "__auto"
    },
    {
     "expr": "progetto_usermanager_1_RAM_USAGE",
     "legendFormat": "__auto"
    },
    {
     "expr": "progetto_slamanager_1_RAM_USAGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container_Module_CPU_USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "progetto_exporter_1_CPU_USAGE", "legendFormat": "__auto" },
    { "expr": "progetto_consumer_1_CPU_USAGE", "legendFormat": "__auto" },
    { "expr": "progetto_notifier_1_CPU_USAGE", "legendFormat": "__auto" },
    { "expr": "progetto_producer_1_CPU_USAGE", "legendFormat": "__auto" },
    { "expr": "progetto_sarima_1_CPU_USAGE", "legendFormat": "__auto" },
    {
     "expr": "progetto_slamanager_1_CPU_USAGE",
     "legendFormat": "__auto"
    },
    {
     "expr": "progetto_subscriber_1_CPU_USAGE",
     "legendFormat": "__auto"
    },
    {
     "expr": "progetto_usermanager_1_CPU_USAGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM_USAGE",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "RAM_CONSUMER_USAGE", "legendFormat": "__auto" },
    { "expr": "RAM_EXPORTER_USAGE", "legendFormat": "__auto" },
    { "expr": "RAM_NOTIFIER_USAGE", "legendFormat": "__auto" },
    { "expr": "RAM_PRODUCER_USAGE", "legendFormat": "__auto" },
    { "expr": "RAM_SERVER_USAGE", "legendFormat": "__auto" },
    { "expr": "RAM_SLA_USAGE", "legendFormat": "__auto" },
    { "expr": "RAM_SUBSCRIBER_USAGE", "legendFormat": "__auto" },
    { "expr": "RAM_SARIMA_USAGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU_USAGE",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    { "expr": "CPU_CONSUMER_USAGE", "legendFormat": "__auto" },
    { "expr": "CPU_EXPORTER_USAGE", "legendFormat": "__auto" },
    { "expr": "CPU_NOTIFIER_USAGE", "legendFormat": "__auto" },
    { "expr": "CPU_PRODUCER_USAGE", "legendFormat": "__auto" },
    { "expr": "CPU_SERVER_USAGE", "legendFormat": "__auto" },
    { "expr": "CPU_SLA_USAGE", "legendFormat": "__auto" },
    { "expr": "CPU_SUBSCRIBER_USAGE", "legendFormat": "__auto" },
    { "expr": "CPU_SARIMA_USAGE", "legendFormat": "__auto" }
   ]
  }
 ]
}