FROM python:3.10-alpine

# Aggiungi i pacchetti necessari per la compilazione di psutil
RUN apk add --no-cache \
    gcc \
    musl-dev \
    linux-headers

ENV SIGN_KEY_USERMANAGER 6bf8fc1cd839b1acc48d4c5b3898d528
ENV SIGN_KEY_USERMANAGER_ADMIN 6bf8fc1cd839b1acc48d4c5b3898d529
ENV PORT 5000
ENV HOST usermanager

WORKDIR /userManager

COPY . .

# Installa le dipendenze
RUN pip install -r requirements.txt

CMD ["python", "usermanager.py"]
