# Use a base image with Python and other dependencies
FROM python:3.10-slim

ENV PORT 5555
ENV HOST sarima

# Set the working directory
WORKDIR /SARIMA

# Copy the requirements file into the container
COPY requirements.txt .

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Set the command to run your application
CMD ["python", "sarima.py"]
