# my global config
global:
  scrape_interval: 20s
  scrape_timeout: 15s
  evaluation_interval: 20s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  
scrape_configs:
  - job_name: "prometheus"
    scheme: https
    static_configs:
      - targets: ["exporter:2000"]
    tls_config:
      cert_file: ./cert.pem
      key_file: ./key.pem
      insecure_skip_verify: true