apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      initContainers:
      - name: wait-db
        image: busybox:1.31
        command: ['sh', '-c', 'until nc -zv db 3306 && nc -zv producer 1000; do echo "Waiting for MySQL and producer"; sleep 5; done;']
      hostname: consumer
      containers:
        - name: consumer
          image: progetto-consumer:latest
          env:
            - name: PORT
              value: "6000"
            - name: HOST
              value: "consumer"
            - name: SIGN_KEY_CONSUMER
              value: "6bf8fc1cd839b1acc48d4c5b3898d526"
          imagePullPolicy: Never
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: NodePort


