apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      initContainers:
      - name: wait-db
        image: busybox:1.31
        command: ['sh', '-c', 'until nc -zv db 3306 && nc -zv consumer 6000; do echo "Waiting for MySQL and consumer"; sleep 5; done;']
      hostname: notifier
      containers:
        - name: notifier
          image: progetto-notifier:latest
          env:
            - name: PORT
              value: "4000"
            - name: HOST
              value: "notifier"
            - name: SIGN_KEY_CONSUMER
              value: "6bf8fc1cd839b1acc48d4c5b3898d526"
            - name: SIGN_KEY_NOTIFIER
              value: "6bf8fc1cd839b1acc48d4c5b3898d525"
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: notifier
spec:
  selector:
    app: notifier
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort


