apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      initContainers:
      - name: wait-db
        image: busybox:1.31
        command: ['sh', '-c', 'until nc -zv db 3306; do echo "Waiting for MySQL"; sleep 5; done;']
      containers:
      - image: phpmyadmin/phpmyadmin:latest
        name: phpmyadmin
        env:
          - name: PMA_HOST
            value: db
          - name: PMA_PORT
            value: '3306'
          - name: PMA_USER
            value: 'root'
          - name: PMA_PSW
            value: ''
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
      nodePort: 30001
  type: NodePort
