apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      initContainers:
      - name: wait-kafka
        image: busybox:1.31
        command: ['sh', '-c', 'until nc -zv kafka 9092; do echo "Waiting for Kafka"; sleep 5; done;']
      hostname: producer
      containers:
        - name: producer
          image: progetto-producer:latest
          env:
            - name: PORT
              value: "1000"
            - name: HOST
              value: "producer"
          imagePullPolicy: Never
          ports:
            - containerPort: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: 1000
      targetPort: 1000
  type: NodePort


