FROM python:3.10-alpine

# Aggiungi i pacchetti necessari per la compilazione di psutil
RUN apk add --no-cache \
    gcc \
    musl-dev \
    linux-headers \
    librdkafka-dev

ENV SIGN_KEY_CONSUMER 6bf8fc1cd839b1acc48d4c5b3898d526
ENV PORT 6000
ENV HOST consumer

WORKDIR /Consumer

COPY . .

RUN pip install -r requirements.txt

CMD ["python", "consumer.py"]
